import { useEffect, useState } from 'react'
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion'
import { gallery, galleryCategories } from '../data/gallery'
import { Close, Arrow } from './Icons'
import { Reveal } from './Motion'

export default function Gallery() {
  const [filter, setFilter] = useState('All'); const [current, setCurrent] = useState(null); const reduce = useReducedMotion()
  const shown = filter === 'All' ? gallery : gallery.filter(item => item.category === filter)
  const index = shown.findIndex(item => item.id === current?.id)
  const move = (direction) => setCurrent(shown[(index + direction + shown.length) % shown.length])
  useEffect(() => { const key = e => { if (!current) return; if (e.key === 'Escape') setCurrent(null); if (e.key === 'ArrowRight') move(1); if (e.key === 'ArrowLeft') move(-1) }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key) })
  return <section className="gallery section container" id="gallery"><Reveal className="section-head"><div><p className="eyebrow">04 — Recent work</p><h2>A close look at<br /><em>the finish.</em></h2></div><p>Every set is a small expression of who you are. Browse a few favourite details.</p></Reveal><div className="filters" role="tablist" aria-label="Gallery categories">{galleryCategories.map(category => <button role="tab" aria-selected={filter === category} key={category} className={filter === category ? 'active' : ''} onClick={() => setFilter(category)}>{category}</button>)}</div><motion.div layout className="gallery-grid">{shown.map((item, i) => <motion.button layout initial={reduce ? false : { opacity: 0, scale: .96 }} animate={reduce ? {} : { opacity: 1, scale: 1 }} exit={reduce ? {} : { opacity: 0, scale: .96 }} transition={{ duration: .35, ease: [0.22, 0.61, 0.36, 1] }} className={`gallery-item gallery-item--${i % 5}`} key={item.id} onClick={() => setCurrent(item)}><img loading="lazy" src={item.src} alt={item.alt} onError={e => { e.currentTarget.style.opacity = '.15' }} /><span><i>{item.category}</i>{item.title}</span></motion.button>)}</motion.div><AnimatePresence>{current && <motion.div className="lightbox" role="dialog" aria-modal="true" aria-label={`${current.title} image`} initial={reduce ? false : { opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><button className="icon-button lightbox__close" onClick={() => setCurrent(null)} aria-label="Close gallery image"><Close /></button><button className="lightbox__prev" onClick={() => move(-1)} aria-label="Previous image"><Arrow /></button><motion.img key={current.id} initial={reduce ? false : { opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .3 }} src={current.src} alt={current.alt} /><button className="lightbox__next" onClick={() => move(1)} aria-label="Next image"><Arrow /></button><p>{current.title} <small>— {current.category}</small></p></motion.div>}</AnimatePresence></section>
}
